# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 555d8ddc592360e319abe0df02f7172dc02da49a64e6d9486fd34da89daba097ed1b067595b4e2a8b46c7698af4375878a2973fa7c778550d7807e40be288b4d

test:
  secret_key_base: 46e98dc84608773c7884cce4d9c54e2d7c112cfec4f3e34bf1b38956f5dd6d184c1986a5290ef5e1d1757a4bde482bd60b544ef3d71521cc88ffd294c54d5e5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
